"""Forge and quest-hall interiors using the six established architectural styles."""
from pathlib import Path
import copy,json
R=Path(__file__).resolve().parents[1]
cities=['Crownford','Sylvaris','Deepforge','Astralis','Crosshaven','Ironroot'];result={}
remove={'Counter','CounterStile','Countertop','JarLabel','JarLid','StockJar','Produce','ProduceBin','Shelf','ShelfPost','ExchangeCoin','AwningStripe','AwningPost'}
for city in cities:
 source=json.loads((R/f'assets/uat01/{city.lower()}-services-v1/kit.json').read_text())
 result[city]={}
 for kind in ['Forge','QuestHall']:
  building=copy.deepcopy(source['buildings']['Market']);parts=building['parts']=[p for p in building['parts'] if p['name']not in remove]
  palette={p['name']:p['color']for p in parts};wood=palette['CeilingBeam'];stone=palette['Floor'];gold=palette['DoorHeader'];iron=[58,66,72];paper=[231,216,174];leather=[114,66,48]
  def add(name,pos,size,color,collision=False,rotation=(0,0,0),shape='Block'):
   parts.append(dict(name=name,position=pos,size=size,color=color,collision=collision,rotation=rotation,shape=shape))
  if kind=='Forge':
   add('FurnaceBase',(0,.7,-8),(8,1.4,5),stone,True)
   for x in [-3.25,3.25]:add('FurnacePier',(x,3.2,-8),(1.5,4,5),stone,True)
   add('FurnaceArch',(0,5.5,-8),(8,1,5),stone,True)
   add('FurnaceBack',(0,3.1,-10.3),(5.2,4,.45),iron,True)
   add('FurnaceHood',(0,8.8,-8.4),(6,5.6,4),iron)
   add('ForgeChimney',(0,19,-8.4),(3.5,15,3.5),stone)
   for y in [14,19,24]:add('ChimneyCollar',(0,y,-8.4),(4,.45,4),gold)
   add('ChimneyCap',(0,26.6,-8.4),(4.8,.55,4.8),stone)
   for x in [-2,-1,0,1,2]:
    add('FurnaceBar',(x,2.0,-5.8),(.18,2.3,.18),iron)
    add('ForgeEmber',(x,1.65,-7.5),(.8,.35,1.9),[242,121,43],shape='Ball')
   add('AnvilStump',(-8,1.1,0),(3,2.2,3),wood,True,shape='Cylinder',rotation=(0,0,90))
   add('AnvilBase',(-8,2.45,0),(3.4,.5,2.7),iron,True)
   add('AnvilWaist',(-8,2.95,0),(1.7,.6,1.7),iron,True)
   add('AnvilFace',(-8,3.45,0),(4.2,.4,2.2),[123,133,137],True)
   add('AnvilHorn',(-5.8,3.35,0),(1.4,.6,1.0),iron,False,(0,0,-12),'Ball')
   add('QuenchBase',(9,.55,0),(4,1.1,4),wood,True)
   for side in [-1,1]:
    add('QuenchWallX',(9+side*1.8,1.5,0),(.35,2.5,4),wood,True)
    add('QuenchWallZ',(9,1.5,side*1.8),(4,2.5,.35),wood,True)
   add('QuenchWater',(9,2.1,0),(3.3,.08,3.3),[62,111,124])
   add('ToolRack',(-9,5.4,-10.5),(7,3,.25),wood)
   for x in [-11,-9,-7]:
    add('ToolHandle',(x,5.3,-10.0),(.18,1.9,.18),leather)
    add('ToolHead',(x,6.05,-10.0),(1.1,.4,.45),iron)
   add('StockBench',(9,2.9,-8),(7,.6,4),wood,True)
   for x in [6.2,11.8]:add('StockBenchLeg',(x,1.4,-8),(.5,2.8,3),wood,True)
   for x in [7.4,9,10.6]:
    for y in [3.5,4.0]:add('Ingot',(x,y,-8),(1.3,.45,2),[171,135,79])
   add('ForgeSignHandle',(-.6,9.1,12.8),(.28,1.8,.23),gold,rotation=(0,0,-25))
   add('ForgeSignHammer',(-.2,9.8,12.8),(1.6,.65,.3),gold,rotation=(0,0,-25))
  else:
   add('CharterDesk',(0,3.0,-8),(16,.5,4),wood,True)
   for x in [-6,6]:add('CharterDeskPedestal',(x,1.5,-8),(3,2.8,3.5),wood,True)
   add('CharterPaper',(0,3.28,-7.4),(3.5,.03,2.2),paper)
   add('CharterSeal',(1.1,3.32,-6.9),(.05,.48,.48),[170,53,48],shape='Cylinder',rotation=(0,0,90))
   add('InkBottle',(-2.7,3.5,-7.6),(.4,.45,.4),[44,58,77],shape='Cylinder',rotation=(0,0,90))
   for side in [-1,1]:
    add('NoticeBoard',(side*13.8,6.4,-1),(.3,5,9),wood)
    for z in [-3.8,-1,1.8]:
     add('QuestNotice',(side*13.58,6.4,z),(.05,3.6,2.1),paper)
     for y in [5.6,6.3,7]:add('NoticeWriting',(side*13.54,y,z),(.02,.1,1.4),leather)
    for z in [0,5.5]:
     add('HallBench',(side*9,1.6,z),(4.5,.45,2.2),wood,True)
     for x in [-1.6,1.6]:add('HallBenchLeg',(side*9+x,.8,z),(.4,1.6,1.7),wood,True)
     add('HallBenchBack',(side*9,2.6,z-1),(4.5,1.6,.3),wood,True)
    add('ArchiveShelf',(side*10,5,-10.6),(5,.3,.8),wood)
    for k in range(7):add('ArchiveBook',(side*10-2+k*.6,5.75,-10.55),(.45,1.2,.6),gold if k%2 else leather)
   add('CharterBanner',(0,7.5,-10.9),(4.6,4.8,.1),wood)
   for angle in [-35,35]:add('CharterEmblem',(0,7.6,-10.78),(.3,3,.15),gold,rotation=(0,0,angle))
   add('QuestSignScroll',(0,9.3,12.8),(2,1.5,.2),paper)
   for x in [-1.1,1.1]:add('QuestScrollRoll',(x,9.3,12.8),(.25,1.9,.3),gold)
  building['identity']=city+' '+kind+' architecture';result[city][kind]=building
 out=R/f'assets/uat01/{city.lower()}-institutions-v1';out.mkdir(parents=True,exist_ok=True)
 (out/'kit.json').write_text(json.dumps({**source,'buildings':result[city]},indent=2)+'\n')
def lua(v):
 if isinstance(v,dict):return '{'+','.join('['+json.dumps(k)+']='+lua(x)for k,x in v.items())+'}'
 if isinstance(v,(list,tuple)):return '{'+','.join(lua(x)for x in v)+'}'
 if isinstance(v,bool):return 'true'if v else'false'
 return json.dumps(v)
(R/'src/shared/Presentation/CivicInstitutionArchitecture.luau').write_text('--!strict\n-- Generated by tools/build_civic_institutions.py.\nreturn '+lua(result)+'\n')
print({city:{kind:len(b['parts'])for kind,b in buildings.items()}for city,buildings in result.items()})
