"""Original epilogue tableaus shared by native UI and editable Blender exports."""
from pathlib import Path
import json, math
root=Path(__file__).resolve().parents[1];out=root/'assets/uat01/archive-endings';out.mkdir(parents=True,exist_ok=True)
colors={'ivory':[224,212,181],'navy':[48,62,78],'brass':[193,153,78],'wood':[130,88,61],'teal':[59,169,154],'coral':[192,103,81],'leaf':[92,143,87],'paper':[241,227,193],'stone':[116,133,139]}
assets=[]
def box(a,n,s,p,c,rz=0):a['parts'].append(dict(name=n,size=s,position=p,color=c,rotation=[0,0,rz]))
def shelf(a,x,z):
 for dx in [-2,2]:box(a,'CabinetSide',[.4,7,2],[x+dx,3.5,z],'wood')
 for y in [.25,2.5,4.8,7]:box(a,'Shelf',[4.6,.35,2.4],[x,y,z],'brass')
 for y in [1.4,3.7,5.95]:
  for dx in [-1.3,0,1.3]:box(a,'ProtectedNames',[.85,1.6,1.4],[x+dx,y,z],'paper')
def bench(a,x,z):
 box(a,'Seat',[6,.4,2],[x,1.8,z],'wood')
 for dx in [-2.4,2.4]:box(a,'SeatLeg',[.5,1.7,1.6],[x+dx,.85,z],'brass')
def ring(a,y,z,color):
 for i in range(12):
  t=i*math.pi/6;box(a,'ArchiveRing',[2.45,.45,.65],[4.5*math.cos(t),y+4.5*math.sin(t),z],color,i*30+90)
def tree(a,x,z):
 box(a,'LivingTrunk',[1.2,6,1.2],[x,3,z],'wood')
 for dx,y in [(-1.7,6),(1.4,7),(0,8.2)]:box(a,'Canopy',[4,2.4,3.6],[x+dx,y,z],'leaf',dx*7)
for identity in ['preserve','transform','dismantle']:
 a={'id':identity,'kind':'EpilogueTableau','parts':[]};assets.append(a)
 box(a,'Floor',[32,1,28],[0,-.5,0],'navy')
 for x in [-14,14]:
  box(a,'Column',[1.5,12,1.5],[x,6,-11],'ivory');box(a,'Capital',[2.4,.7,2.4],[x,12,-11],'brass')
 box(a,'OpenLintel',[30,1.4,2],[0,12.8,-11],'ivory')
 for z in [-10,-5,0,5,10]:box(a,'SharedWalkway',[6,.05,4.5],[0,.04,z],'stone')
 if identity=='preserve':
  ring(a,6,-10,'brass')
  for x in [-10,10]:
   for z in [-5,4]:shelf(a,x,z)
  box(a,'RecordDesk',[8,.5,3.5],[0,3.2,7],'wood')
  for x in [-3,3]:box(a,'DeskLeg',[.7,3,.7],[x,1.5,7],'brass')
  box(a,'OpenLedger',[3,.2,2],[0,3.6,7],'paper')
 elif identity=='transform':
  ring(a,6,-10,'teal')
  for x in [-9,9]:
   for z in [-3,5]:
    box(a,'RefugeBed',[5,1,6],[x,.7,z],'wood');box(a,'Mattress',[4.7,.5,5.7],[x,1.4,z],'paper');box(a,'Blanket',[4.8,.12,3.4],[x,1.72,z+.8],'coral');box(a,'Pillow',[3,.3,1.4],[x,1.8,z-1.8],'ivory')
  bench(a,0,7);tree(a,-10,-9);tree(a,10,-9)
 else:
  tree(a,0,-8)
  for x in [-10,10]:shelf(a,x,-5);bench(a,x,7)
  shelf(a,0,-11)
  for i in range(6):box(a,'RecoveredEngineSection',[2.4,.45,.65],[-10+(i%3)*2.8,.6+(i//3)*.65,1],'brass')
  for x in [-10,10]:
   box(a,'GardenBed',[6,.7,3],[x,.4,1],'wood')
   for dx in [-2,0,2]:box(a,'GardenLeaf',[1.1,1.5,1.1],[x+dx,1.3,1],'leaf',20);box(a,'Flower',[.8,.4,.8],[x+dx,2.2,1],'coral')
(out/'kit.json').write_text(json.dumps({'schema':1,'units':'stud','upAxis':'Y','palette':colors,'assets':assets},indent=2)+'\n',encoding='utf-8')
v=lambda x:'Vector3.new('+','.join(map(str,x))+')'
lines=['--!strict','-- Generated by tools/build_archive_endings.py; presentation only, no collision or rewards.','local definitions:{[string]:{{any}}}={']
for a in assets:
 lines.append(a['id']+'={')
 for p in a['parts']:lines.append('{'+json.dumps(p['name'])+','+v(p['size'])+','+v(p['position'])+',Color3.fromRGB('+','.join(map(str,colors[p['color']]))+'),'+str(p['rotation'][2])+'},')
 lines.append('},')
lines+=['}','return function(id:string):Model?','local list=definitions[id];if not list then return nil end','local m=Instance.new("Model");m.Name="ArchiveEnding_"..id;m.WorldPivot=CFrame.identity;m:SetAttribute("Ending",id)','for _,d in ipairs(list)do local p=Instance.new("Part");p.Name=d[1];p.Size=d[2];p.CFrame=CFrame.new(d[3])*CFrame.Angles(0,0,math.rad(d[5]));p.Color=d[4];p.Material=Enum.Material.SmoothPlastic;p.Anchored=true;p.CanCollide=false;p.CanQuery=false;p.CanTouch=false;p.TopSurface=Enum.SurfaceType.Smooth;p.BottomSurface=Enum.SurfaceType.Smooth;p.Parent=m end','return m','end']
(root/'src/shared/Presentation/ArchiveEndingKit.luau').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('ENDING_KIT',len(assets),sum(len(a['parts'])for a in assets),'parts')

