"""Five original weapon geometries, shared between native Roblox and Blender exports."""
from pathlib import Path
import json,math
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'assets/uat01/weapon-kit'
palette={'wood':[99,65,43],'leather':[74,43,35],'steel':[181,199,205],'gold':[209,171,84],
    'copper':[177,119,63],'blue':[92,158,195],'cyan':[82,191,209],'ivory':[239,223,179],'leaf':[121,159,79]}
assets=[]
def asset(id):
    a={'id':id,'pivot':'grip','parts':[]};assets.append(a);return a['parts']
def box(p,name,size,at,color,rz=0):p.append({'name':name,'size':size,'position':at,'rotation':[0,0,rz],'color':color})
def beam(p,name,a,b,width,color):
    dx,dy=b[0]-a[0],b[1]-a[1]
    box(p,name,[width,math.hypot(dx,dy),width],[(a[0]+b[0])/2,(a[1]+b[1])/2,0],color,-math.degrees(math.atan2(dx,dy)))
for id,tint,width in [('watchblade','copper',.48),('oathblade','blue',.62)]:
    p=asset(id);box(p,'Grip',[.28,.82,.28],[0,0,0],'leather')
    box(p,'Pommel',[.44,.28,.38],[0,-.54,0],tint,45)
    box(p,'Guard',[1.35,.18,.35],[0,.51,0],tint)
    box(p,'Blade',[width,2.5,.15],[0,1.88,0],'steel')
    box(p,'Fuller',[.11,1.85,.17],[0,1.8,0],tint)
    for side in (-1,1):
        box(p,'Point',[.15,.55,width/2],[side*width/4,3.405,0],'steel')
        p[-1]['shape']='Wedge';p[-1]['rotation']=[0,-side*90,0]
    box(p,'GuardGem',[.26,.26,.13],[0,.52,-.24],tint,45)
    for side in (-1,1):
        box(p,'GuardWing',[.38,.16,.32],[side*.72,.57,0],tint,side*22)
    if id=='oathblade':
        for side in (-1,1):box(p,'BladeShoulder',[.2,.58,.16],[side*.39,.86,0],'steel',side*-12)

p=asset('yew_longbow')
points=[(-1.05,-2.3),(-.3,-1.4),(0,0),(-.3,1.4),(-1.05,2.3)]
for i in range(4):beam(p,'YewLimb',points[i],points[i+1],.21,'wood')
beam(p,'String',points[0],points[-1],.035,'ivory');box(p,'Grip',[.3,.65,.34],[0,0,0],'leather')
for side in (-1,1):
    box(p,'TipCap',[.25,.22,.27],[-1.05,side*2.3,0],'gold',side*30)
    box(p,'LeafInlay',[.26,.48,.1],[-.2,side*.85,-.16],'leaf',side*18)

p=asset('tide_staff')
box(p,'Shaft',[.2,4.3,.2],[0,.45,0],'wood');box(p,'Grip',[.29,.75,.29],[0,0,0],'leather')
box(p,'Butt',[.35,.22,.35],[0,-1.79,0],'steel');box(p,'Collar',[.6,.25,.5],[0,2.55,0],'steel')
box(p,'Focus',[.6,.8,.55],[0,3.13,0],'cyan',45)
for side in (-1,1):
    box(p,'WaveArm',[.18,1,.24],[side*.5,2.99,0],'steel',-side*22)
    box(p,'WaveTip',[.38,.17,.24],[side*.58,3.47,0],'cyan',side*25)
box(p,'LowerRune',[.13,.65,.1],[0,1.55,-.17],'cyan')

p=asset('dawn_crozier')
box(p,'Shaft',[.2,4.1,.2],[0,.4,0],'wood');box(p,'Grip',[.29,.75,.29],[0,0,0],'leather')
box(p,'Butt',[.32,.23,.32],[0,-1.76,0],'gold');box(p,'Collar',[.55,.22,.45],[0,2.44,0],'gold')
for i in range(6):
    a=-math.pi/2+i*math.pi/4;b=a+math.pi/4
    beam(p,'CrozierArc',(.6*math.cos(a),3.06+.6*math.sin(a)),(.6*math.cos(b),3.06+.6*math.sin(b)),.16,'gold')
box(p,'Focus',[.36,.5,.34],[0,3.06,0],'ivory',45)
box(p,'SunRay',[1.2,.12,.14],[0,3.06,0],'gold')

OUT.mkdir(parents=True,exist_ok=True)
(OUT/'kit.json').write_text(json.dumps({'version':1,'units':'stud','upAxis':'Y','palette':palette,'assets':assets},indent=2)+'\n',encoding='utf-8')
lines=['--!strict','-- Generated by tools/build_weapon_kit.py. Visuals only; no item grants or stats.','local V=Vector3.new','type Piece={name:string,size:Vector3,position:Vector3,rotation:Vector3,color:Color3,kind:string}','local definitions: {[string]: {Piece}}={']
for asset in assets:
    lines.append('\t["'+asset['id']+'"]={')
    for p in asset['parts']:
        vec=lambda x:'V('+','.join(str(round(v,5)) for v in x)+')'
        lines.append('\t\t{name='+json.dumps(p['name'])+',size='+vec(p['size'])+',position='+vec(p['position'])+',rotation='+vec(p['rotation'])+',kind='+json.dumps('WedgePart' if p.get('shape')=='Wedge' else 'Part')+',color=Color3.fromRGB('+','.join(map(str,palette[p['color']]))+')},')
    lines.append('\t},')
lines+=['}','return function(id: string): Model?','\tlocal data=definitions[id];if not data then return nil end',
'\tlocal m=Instance.new("Model");m.Name=id;m.WorldPivot=CFrame.identity;m:SetAttribute("OriginalWeaponId",id)',
'\tfor _,v in ipairs(data) do local p=Instance.new(v.kind) :: BasePart;p.Name=v.name;p.Size=v.size;p.CFrame=CFrame.new(v.position)*CFrame.Angles(math.rad(v.rotation.X),math.rad(v.rotation.Y),math.rad(v.rotation.Z));p.Color=v.color',
'\t\tp.Material=Enum.Material.SmoothPlastic;p.Anchored=true;p.CanCollide=false;p.CanTouch=false;p.CanQuery=false;p.Massless=true;p.Parent=m end',
'\treturn m','end','']
(ROOT/'src/server/Services/WeaponVisuals.luau').write_text('\n'.join(lines),encoding='utf-8')
print('WEAPON_KIT_CREATED',len(assets),'weapons',sum(len(a['parts']) for a in assets),'parts; grip pivots')
