"""Original freestanding guild furniture; shared source for native and Blender previews."""
from pathlib import Path
import json, math

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets/uat01/furniture-kit'
OUT.mkdir(parents=True,exist_ok=True)
P={'wood':[121,80,51],'dark':[64,46,38],'ivory':[235,225,202],'gold':[212,170,82],
   'navy':[46,68,100],'red':[145,61,65],'green':[66,133,94],'stone':[118,133,144],
   'cyan':[100,208,213],'soil':[70,53,39]}
assets=[]
def asset(id,name,th,w,d):
    a=dict(id=id,name=name,nameTH=th,footprint=[w,d],parts=[],runtimeBound=True)
    assets.append(a);return a
def box(a,n,s,p,c,rz=0):
    a['parts'].append(dict(name=n,size=s,position=p,color=c,rotation=[0,0,rz],collide=False))
def legs(a,w,d,h):
    for x in (-w/2+.35,w/2-.35):
        for z in (-d/2+.35,d/2-.35):box(a,'Leg',[.4,h,.4],[x,h/2,z],'dark')

a=asset('hearth_table','Hearth Table','โต๊ะไม้เตาผิง',8,6)
legs(a,7,5,2.8);box(a,'TableTop',[7.5,.4,5.5],[0,3,0],'wood')
box(a,'Runner',[2,.06,5],[0,3.23,0],'navy')
for x in (-2.6,2.6):box(a,'BrassInlay',[.12,.07,4.8],[x,3.24,0],'gold')
a=asset('hearth_chair','Hearth Chair','เก้าอี้ไม้เตาผิง',4,4)
legs(a,2.8,2.8,1.8);box(a,'Seat',[3,.35,3],[0,1.95,0],'wood')
for x in (-1.2,1.2):box(a,'BackPost',[.35,3.8,.35],[x,1.9,-1.2],'dark')
box(a,'BackRest',[2.5,1.2,.35],[0,3.2,-1.2],'navy')
box(a,'Crest',[.55,.55,.15],[0,3.2,-.96],'gold',45)
a=asset('welcome_bench','Welcome Bench','ม้านั่งต้อนรับ',8,4)
legs(a,7,2.8,1.8);box(a,'Seat',[7.5,.4,3.2],[0,2,0],'wood')
for x in (-3.1,3.1):box(a,'BackPost',[.4,3.8,.4],[x,1.9,-1.2],'dark')
box(a,'BackRest',[7,1,.3],[0,3.2,-1.2],'green')
for x in (-2,0,2):box(a,'WelcomeDiamond',[.5,.5,.15],[x,3.2,-.95],'gold',45)
a=asset('guild_bookcase','Guild Bookcase','ตู้หนังสือกิลด์',6,4)
for x in (-2.6,2.6):box(a,'Side',[.4,7,2.6],[x,3.5,0],'dark')
for y in (.2,2.4,4.6,6.8):box(a,'Shelf',[5.6,.35,2.8],[0,y,0],'wood')
box(a,'Back',[5.6,7,.2],[0,3.5,-1.3],'dark')
for y in (1.3,3.5,5.7):
    for i in range(4):box(a,'Book',[.65,1.65,1.6],[-1.8+i*1.15,y,0],['navy','red','green','ivory'][i])
a=asset('woven_rug','Compass Rug','พรมเข็มทิศ',8,8)
box(a,'Rug',[7.6,.08,7.6],[0,.04,0],'navy')
for x in (-3.5,3.5):box(a,'Edge',[.15,.03,7.1],[x,.095,0],'gold')
for z in (-3.5,3.5):box(a,'Edge',[7.1,.03,.15],[0,.095,z],'gold')
box(a,'North',[.3,.04,3.5],[0,.11,0],'ivory');box(a,'East',[3.5,.04,.3],[0,.11,0],'gold')
a=asset('guild_banner','Standing Guild Banner','ธงกิลด์ตั้งพื้น',4,4)
box(a,'Foot',[3,.3,3],[0,.15,0],'stone');box(a,'Pole',[.3,7,.3],[0,3.5,0],'dark')
box(a,'Crossbar',[3.6,.25,.3],[0,6.5,0],'gold');box(a,'Cloth',[3.2,4,.12],[0,4.5,.1],'navy')
box(a,'Crest',[1,1,.15],[0,4.8,.2],'gold',45)
a=asset('garden_planter','Garden Planter','กระบะสวน',6,4)
box(a,'Base',[5.4,.3,3.4],[0,.15,0],'wood');box(a,'Soil',[4.8,.3,2.8],[0,1.1,0],'soil')
for x in (-2.5,2.5):box(a,'End',[.4,1.5,3.4],[x,.75,0],'wood')
for z in (-1.5,1.5):box(a,'Side',[5.4,1.5,.4],[0,.75,z],'wood')
for x in (-1.5,0,1.5):
    box(a,'Stem',[.15,1.8,.15],[x,1.8,0],'green')
    for s in (-1,1):box(a,'Leaf',[.3,1,.7],[x+s*.35,2.1,0],'green',s*45)
    box(a,'Flower',[.55,.4,.55],[x,2.85,0],'gold')
a=asset('crystal_lantern','Crystal Lantern','โคมผลึก',4,4)
box(a,'Foot',[2,.25,2],[0,.125,0],'stone');box(a,'Post',[.35,4,.35],[0,2,0],'dark')
box(a,'Base',[1.7,.25,1.7],[0,4,0],'gold');box(a,'Glow',[1,1.4,1],[0,4.8,0],'cyan')
for x in (-.65,.65):
    for z in (-.65,.65):box(a,'Frame',[.12,1.6,.12],[x,4.8,z],'gold')
box(a,'Cap',[1.8,.3,1.8],[0,5.7,0],'navy')
a=asset('display_plinth','Display Plinth','แท่นจัดแสดง',4,4)
box(a,'Base',[3.6,.4,3.6],[0,.2,0],'stone');box(a,'Column',[2.6,2.2,2.6],[0,1.5,0],'stone')
box(a,'Top',[3.6,.35,3.6],[0,2.775,0],'gold');box(a,'Cushion',[3,.15,3],[0,3.025,0],'red')
a=asset('hearth_bed','Hearth Bed','เตียงไม้เตาผิง',6,8)
legs(a,5,7,1);box(a,'Frame',[5.5,.5,7.4],[0,1,0],'wood')
box(a,'Mattress',[5,.5,7],[0,1.5,0],'ivory');box(a,'Blanket',[5.05,.15,4.4],[0,1.82,1.15],'navy')
box(a,'Pillow',[3.6,.45,1.3],[0,1.95,-2.5],'ivory')
box(a,'Headboard',[5.5,2.8,.35],[0,1.4,-3.65],'wood')

for a in assets:
    w,d=a['footprint']
    for p in a['parts']:
        angle=math.radians(p['rotation'][2]);sx,sy,sz=p['size'];x,y,z=p['position']
        ex=abs(math.cos(angle))*sx/2+abs(math.sin(angle))*sy/2
        ey=abs(math.sin(angle))*sx/2+abs(math.cos(angle))*sy/2
        assert abs(x)+ex<=w/2+1e-6 and abs(z)+sz/2<=d/2+1e-6,(a['id'],p['name'])
        assert y-ey>=-1e-6,(a['id'],p['name'],'below floor')
(OUT/'kit.json').write_text(json.dumps(dict(schema=1,units='stud',palette=P,assets=assets),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
v=lambda xyz:'Vector3.new('+','.join(map(str,xyz))+')'
lines=['--!strict','-- Generated by tools/build_furniture_kit.py; native geometry only; ownership and collision are handled by runtime services.','return function():Folder','local folder=Instance.new("Folder");folder.Name="FurnitureKit"']
for a in assets:
    lines+=['do local m=Instance.new("Model");m.Name='+json.dumps(a['id'])+';m.WorldPivot=CFrame.identity;m.Parent=folder',
            'm:SetAttribute("FootprintWidth",'+str(a['footprint'][0])+');m:SetAttribute("FootprintDepth",'+str(a['footprint'][1])+')']
    for p in a['parts']:
        lines+=['do local p=Instance.new("Part");p.Name='+json.dumps(p['name'])+';p.Size='+v(p['size'])+';p.CFrame=CFrame.new('+v(p['position'])+')*CFrame.Angles(0,0,math.rad('+str(p['rotation'][2])+'));p.Color=Color3.fromRGB('+','.join(map(str,P[p['color']]))+');p.Material=Enum.Material.SmoothPlastic;p.Anchored=true;p.CanCollide=false;p.CanTouch=false;p.CanQuery=false;p.Parent=m end']
    lines+=['end']
lines+=['return folder','end']
(ROOT/'review/FurnitureKit.luau').write_text('\n'.join(lines)+'\n',encoding='utf-8')
(ROOT/'src/shared/Presentation/FurnitureKit.luau').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('FURNITURE_KIT',len(assets),'models',sum(len(a['parts']) for a in assets),'parts; all footprints checked')
