"""Append the latest verified library/AI evidence, preserving historical checkpoints."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
note='''## Latest checkpoint — 2026-10-02 regional prototypes and complete visual libraries

Quota78% used/22% remaining; continue useful work toward15%. Current Studio is Edit, all owned Play stopped, review fixtures removed, camera/FOV restored. No publish/upload/commerce, no ordinary profile rewards/migration.

Hero art:15original templates matching registry IDs,439visible parts/5268triangles,16bones each,60clips,90exports round-trip PASS.15individual.blends plus gallery/portraits. Native HeroVisualKit static439parts or rigged679parts/225motors/439welds; both modes Studio-verified. Rigged templates in ServerStorage.HeroVisualKit. No recruitment ownership/follow/combat binding. See hero-kit/README.md and validation-hero-*.

Cosmetic art:8models/106parts/1272triangles,8transparent512icons(min55pxmargin),16mesh exports round-trip PASS,editable.blend; native ServerStorage.CosmeticVisualKit verified. Additional2s61frame FriendlyGreeting custom-rig animation exported/reimported with raised hand/stationary root/return-to-rest PASS. FBX frame range starts2, so verifier uses actual imported bounds. Portal/trail remain static prototypes; entitlement/shop/equip and dynamic effect delivery pending. See cosmetic-kit/README.md.

Registry reconciliation now preserves239asset/65screen rows while marking30native inventory previews,15visual hero templates and8cosmetic art slots with explicit unfinished bindings. No UAT approval or cloud ID fabricated. PRODUCTION_LIBRARIES.md and intake/production-libraries.json inventory8libraries/429files with hashes; counts overlap and are not unique gameplay assets.

AdventureScene connects3maps to12correct art actors (one boss each), isolated and unparented until requested. AdventurePatterns defines6boss attacks plus boar/hound/caster patterns: fixed targeting, circle/ring/line/cone geometry, half-health alternate phases, recovery/cancel and late-tick expiry. AdventureEnemyBrain adds bounded movement/leash/owner+alive+visibility target filters, ranged spacing, support healing and cooldowns. AdventureEncounterPreview uses actual map raycasts/art and synthetic combat records only.12actor fixture passes attacks/healing and both patterns for each boss; final renderer-integrated rerun also passed. No player adapter, production damage mitigation, charge displacement, specialized guard mitigation, rewards, region travel or persistent quest events are claimed. This remains prototype integration, not three completed adventures.

AdventureTelegraph native outline renderer verified Circle32/Ring64/Line4/Cone26noninteractive parts; perimeter approximations conservatively enclose circular damage. Screenshot adventure-telegraphs.png; gallery cleaned. Final warning cleanup type annotation corrected and synced.

319domain tests including5000marketorders passed in validation-adventure-full.txt (strict stage initially failed on warning=nil inference). Follow-up validation-adventure-final.txt strict PASS plus fresh build/compile/repository PASS123strictfiles. Earlier standalone319run in validation-adventure-brain.txt also PASS. No need to rerun soak for documentation-only work. All new source synchronized to Studio.

'''
p=root/'docs/uat01/HANDOFF.md';s=p.read_text(encoding='utf-8');p.write_text(note+s if note not in s else s,encoding='utf-8')
for name in ['STATUS.md','WORK_CHECKLIST.md']:
    p=root/'docs/uat01'/name;s=p.read_text(encoding='utf-8').replace('309tests','319tests').replace('309 tests','319 tests').replace('last observed23% remaining','last observed22% remaining');p.write_text(s,encoding='utf-8')
p=root/'docs/uat01/WORK_CHECKLIST.md';s=p.read_text(encoding='utf-8').replace('15 actual templates, weekly rotation, earned bound tickets,1/10 flow and v2 gate','15visual templates/rigs created; actual recruitment bindings,weekly rotation,earned bound tickets,1/10 flow and v2 gate').replace('| Cosmetics |8 concept designs |','| Cosmetics |8native/Blender art prototypes,8icons and one2s greeting animation verified |');p.write_text(s,encoding='utf-8')
p=root/'docs/uat01/ASSET_MANIFEST.md';s=p.read_text(encoding='utf-8').replace('Fourteen PNGs','Fifteen PNGs').replace('| guildborne-bestiary-concepts-v1 | 9 enemies + 3 bosses | Models/AI/encounters pending |','| guildborne-bestiary-concepts-v1 |9enemies+3bosses |12rigs/48clips created; isolated AI prototype tested; live encounter integration pending |').replace('| guildborne-hero-templates-v1 | 15 hero visual proposals | Model/rig production pending |','| guildborne-hero-templates-v1 |15hero visual proposals |15models/rigs/60clips created; recruitment binding pending |').replace('| guildborne-cosmetic-concepts-v1 | 8 cosmetic proposals | Modeling, entitlements and shop implementation pending |','| guildborne-cosmetic-concepts-v1 |8cosmetic proposals |8art models/icons and greeting clip created; entitlements/shop/dynamic VFX pending |');s+='\nCurrent portable/native library evidence: [production ledger](PRODUCTION_LIBRARIES.md).\n';p.write_text(s,encoding='utf-8')
p=root/'assets/uat01/GALLERY.md';s=p.read_text(encoding='utf-8');line='\n[15hero visual templates and60clips](hero-kit/README.md) · [8cosmetic art prototypes and greeting animation](cosmetic-kit/README.md). No recruitment or shop entitlement is implied.\n';p.write_text(s+line if line not in s else s,encoding='utf-8')
