from pathlib import Path
root=Path('.')
header='> Fresh finale and UX checkpoint — 2026-10-06: full Chapter00–06 desktop Memory journey passed with ordinary input, no source hotpatch/profile grants: revision266, Mage100/5015XP, Hall17, 568Gold, 36 campaign +6 novice claims. Court/arena cleanup passed; Play stopped. Subsequent completion UI/tracker, combat status/input and shutter preparation polish passes628 domain tests, strict analysis,144 native completion views/882 bounds and isolated54-stud normal-speed shutter run (3 blocks/full health). Eight builds /290 runtime sources. Registry417 assets/33 generated PNGs. Memory progress is not a resumable save; imports, persistence, multiplayer, devices, final art/balance and human release acceptance remain. Quota65%used/35%remaining; continue to25%remaining, save/stop owned work, then normal shutdown.'
for name in ['STATUS.md','HANDOFF.md','WORK_CHECKLIST.md']:
 p=root/'docs/uat01'/name;s=p.read_text(encoding='utf-8');p.write_text(header+'\n\n'+s,encoding='utf-8')
p=root/'docs/uat01/ARCHIVE_HEART_FOUNDATION.md';s=p.read_text(encoding='utf-8').replace('The strongest full fresh-player evidence remains Chapter00–04, revision217 / Hall11. A full ordinary-input Chapter00–06 journey, reconnect and multiplayer acceptance are pending.','A full ordinary-input Chapter00–06 desktop Memory journey now passes at revision266 / Mage100 / Hall17, with no source hotpatch or profile grants. See FRESH_FINALE_PROGRESS.md and per-chapter evidence. Subsequent UI/timing polish is separately tested; reconnect, multiplayer, devices, imports and human acceptance remain pending.');s+='\n## Fresh finale acceptance and subsequent polish\n\nAll36 campaign and6 novice quests completed through ordinary input, including both new boss activities with zero mistakes in observed samples. Return to City removed court/arena. Final Memory state was captured before stopping Play; it is not a resumable save. Campaign ending is Transform. Completion UI now reflects the enabled arc and selected ending, retains active Journal priority and earned Hall permit guidance. Protection preparation increased from1s to4s, duration18s to22s. Subsequent checks:628 domain tests; strict; eight builds;144 completion GUI views/882 bounds; isolated native normal-speed54-stud first-shutter route completed with3 blocks and full health. See validation-fresh-polish-native.json.\n';p.write_text(s,encoding='utf-8')
p=root/'docs/uat01/USAGE_STOP.md';s=p.read_text(encoding='utf-8').replace('Latest observed quota: 62% used / 38% remaining.','Latest observed quota: 65% used / 35% remaining.');p.write_text(s,encoding='utf-8')
p=root/'docs/uat01/WORK_CHECKLIST.md';s=p.read_text(encoding='utf-8');lines=s.splitlines()
for i,line in enumerate(lines):
 if line.startswith('| Quests / NPCs |'):lines[i]='| Quests / NPCs | Fresh Chapter00–06 ordinary-input Memory journey complete: revision266, Mage100, Hall17, 36 campaign +6 novice claims; puzzle/release/transform route. Subsequent completion UI and protection timing separately tested. | Other routes/classes at full-journey scale, companion-follow UX, six-city services, final dialogue/endings, persistent reconnect, multiplayer and device UAT. |'
 elif line.startswith('| Acceptance / release |'):lines[i]='| Acceptance / release | Fresh Chapter00–06 desktop Memory journey; 628 domain tests; 290 runtime sources; eight build variants.144 completion UI views/882 bounds; isolated actual-key shutter timing pass. | Persistence, real2/4-client sessions, physical devices, imported assets, final balance/art, human UAT. Full journey predates latest UI/timing polish. |'
s='\n'.join(lines)+'\n';p.write_text(s,encoding='utf-8')
