"""Record the verified art batch without changing historical release gates."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'docs/uat01/HANDOFF.md';s=p.read_text(encoding='utf-8')
s=s.replace('Walk-motion renderer/encoder available; check walk-preview.gif and validation-enemy-motion.txt for completion.','Walk preview verified:24source frames,15unique visible poses,22encoded frames after adjacent duplicates coalesce;960ms duration. See walk-preview-report.json; no static-clip failure.')
note='''Newest region blockouts: assets/uat01/region-kit has3original walkable map shells,141parts,9review routes,15arrival/encounter markers,3editable.blend+3FBX+3GLB+3PNG. Six exports round-trip checked. Studio ServerStorage.AdventureMapKit installed, not runtime travel/AI bound. studio_region_routes_probe samples2190floors, <=9.09degree ramps and15clear markers; separate standard R15 physical walk probe evidence pending. Fixed coplanar dock/bridge overlap found in rendered review.114strict runtime files. Check validation-region-* and current quota before next batch. Full gameplay remains incomplete.\n\n'''
if note not in s:s=s.replace('## Latest completed checkpoint — 2026-10-02 item library and city navigation\n\n','## Latest completed checkpoint — 2026-10-02 item library and city navigation\n\n'+note)
p.write_text(s,encoding='utf-8')
p=root/'docs/uat01/STATUS.md';s=p.read_text(encoding='utf-8').replace('last observed24% remaining','last observed23% remaining');s=s.replace('Latest: five native weapon models plus verified Blender exports;16frame shockwave atlas; eight city NPC role appearances and per-player quest markers with direct Journal focus.','Latest:30item visual models,8wearable armors/6accessories,12regional enemy rigs/48clips and3walkable map blockouts. Native inventory/wardrobe/NPC/navigation/recovery UI integrated; regional AI/travel not integrated.');p.write_text(s,encoding='utf-8')
p=root/'docs/uat01/WORK_CHECKLIST.md';s=p.read_text(encoding='utf-8').replace('new16-bone Sentinel custom NPC rig and9FBXclips round-trip verified','Sentinel16-bone rig/9clips plus12regional rigs/48clips round-trip verified').replace('Original map concept, native city/travel and223-part decorative archipelago','Original map concept, native city/travel,223-part decorative archipelago;3separate map blockouts/141parts/9routes/15markers').replace('9 distinct adventure archetypes,3 bosses with2 patterns/phases each','12regional art rigs are created;9adventure AI archetypes and3bosses with2patterns/phases each remain').replace('30 items, binding labels, filters/sort/compare/equip/sell confirmation','30items,30native previews/PNGicons/60mesh exports;8armor/6accessory native wearables; filters/sort/compare/equip/sell').replace('30native previews +30transparent PNGs +60mesh exports created/verified; import/balance/device acceptance pending','Import/balance/device acceptance and arbitrary avatar fitting');p.write_text(s,encoding='utf-8')
p=root/'assets/uat01/GALLERY.md';s=p.read_text(encoding='utf-8');line='\nThree original traversable blockouts: [region kit](region-kit/README.md), with9review routes and15encounter markers. Regional gameplay integration remains pending.\n';p.write_text(s+line if line not in s else s,encoding='utf-8')
